#!/bin/sh

MODEL_NAME=$1
BUILD_DIR=$2

NEMO={{NEMO}}
NEST_DIR={{NEST_DIR}}
SUNDIALS_DIR={{SUNDIALS_DIR}}
{% with gsl_dir = default(GSL_DIR, '/usr') %}
GSL_DIR={{gsl_dir}}
{% endwith %}

cd $BUILD_DIR

echo $NEMO --nest --nest-method=gsl Golgi_Solinas08.nemo
$NEMO --nest --nest-method=gsl Golgi_Solinas08.nemo

echo $NEMO --template=nestmodule_bootstrap.sh --template=nestmodule_configure.ac --template=nestmodule_makefile.am --template=nestmodule.cpp --template=nestmodule.h --template=golgimodule.sli --template=testrun.sli Golgi_Solinas08.nemo
$NEMO --template=nestmodule_bootstrap.sh --template=nestmodule_configure.ac --template=nestmodule_makefile.am --template=nestmodule.cpp --template=nestmodule.h --template=golgimodule.sli --template=testrun.sli Golgi_Solinas08.nemo

mv Golgi_nestmodule_bootstrap.sh  bootstrap.sh 
mv Golgi_nestmodule_configure.ac  configure.ac
mv Golgi_nestmodule_makefile.am   Makefile.am
mv Golgi_nestmodule.cpp           golgimodule.cpp
mv Golgi_nestmodule.h             golgimodule.h
mv Golgi_golgimodule.sli          golgimodule.sli

chmod u+x bootstrap.sh

./bootstrap.sh && \
LDFLAGS=-L$SUNDIALS_DIR/lib CXXFLAGS=-I$GSL_DIR/include ./configure --with-nest=$NEST_DIR/bin/nest-config && \
make && \
make uninstall && \
make install
