#!/bin/sh

MODEL_NAME=$1
BUILD_DIR=$2

NEMO={{NEMO}}
NEURON_DIR={{NEURON_DIR}}

cd $BUILD_DIR

echo $NEMO -p --nmodl --nmodl-method=derivimplicit --nmodl-kinetic=Narsg_z Purkinje_Khaliq03.nemo
$NEMO -p --nmodl --nmodl-method=derivimplicit --nmodl-kinetic=Narsg_z Purkinje_Khaliq03.nemo

echo $NEMO -p --vclamp-hoc Purkinje_Khaliq03.nemo
$NEMO -p --vclamp-hoc Purkinje_Khaliq03.nemo

echo $NEMO -p --template=.hoc Purkinje_Khaliq03.nemo
$NEMO -p --template=.hoc Purkinje_Khaliq03.nemo


echo $NEURON_DIR/bin/nrnivmodl
$NEURON_DIR/bin/nrnivmodl

