#!/bin/sh

MODEL_NAME=$1
VERSION=$2
BUILD_DIR=$3

echo svn export --username=anonymous --password='' -r $VERSION  https://code.call-cc.org/svn/chicken-eggs/release/4/nemo/trunk/examples/Purkinje/Purkinje_Khaliq03.nemo $BUILD_DIR/Purkinje_Khaliq03.nemo
svn export --username=anonymous --password='' -r $VERSION  https://code.call-cc.org/svn/chicken-eggs/release/4/nemo/trunk/examples/Purkinje/Purkinje_Khaliq03.nemo $BUILD_DIR/Purkinje_Khaliq03.nemo
