#!/bin/sh

MODEL_NAME=$1
BUILD_DIR=$2

NEMO={{NEMO}}
NEST_DIR={{NEST_DIR}}
SUNDIALS_DIR={{SUNDIALS_DIR}}

cd $BUILD_DIR


echo $NEMO --nest --nest-method=cvode Golgi_DeSouza10.nemo
$NEMO --nest --nest-method=cvode Golgi_DeSouza10.nemo

echo $NEMO --template=nestmodule_bootstrap.sh Golgi_DeSouza10.nemo
$NEMO --template=nestmodule_bootstrap.sh Golgi_DeSouza10.nemo

echo $NEMO --template=nestmodule_configure.ac Golgi_DeSouza10.nemo
$NEMO --template=nestmodule_configure.ac Golgi_DeSouza10.nemo

echo $NEMO --template=nestmodule_makefile.am Golgi_DeSouza10.nemo
$NEMO --template=nestmodule_makefile.am Golgi_DeSouza10.nemo

echo $NEMO --template=nestmodule.cpp Golgi_DeSouza10.nemo
$NEMO --template=nestmodule.cpp Golgi_DeSouza10.nemo

echo $NEMO --template=nestmodule.h Golgi_DeSouza10.nemo
$NEMO --template=nestmodule.h Golgi_DeSouza10.nemo

echo $NEMO --template=drop_odd_spike_connection.h Golgi_DeSouza10.nemo
$NEMO --template=drop_odd_spike_connection.h Golgi_DeSouza10.nemo

echo $NEMO --template=golgimodule.sli Golgi_DeSouza10.nemo
$NEMO --template=golgimodule.sli Golgi_DeSouza10.nemo

echo $NEMO --template=testrun.sli Golgi_DeSouza10.nemo
$NEMO --template=testrun.sli Golgi_DeSouza10.nemo

echo mv Golgi_drop_odd_spike_connection.h drop_odd_spike_connection.h
mv Golgi_drop_odd_spike_connection.h drop_odd_spike_connection.h

echo mv Golgi_nestmodule_bootstrap.sh  bootstrap.sh 
mv Golgi_nestmodule_bootstrap.sh  bootstrap.sh 

echo mv Golgi_nestmodule_configure.ac  configure.ac
mv Golgi_nestmodule_configure.ac  configure.ac

echo mv Golgi_nestmodule_makefile.am   Makefile.am
mv Golgi_nestmodule_makefile.am   Makefile.am

echo mv Golgi_nestmodule.cpp           golgimodule.cpp
mv Golgi_nestmodule.cpp           golgimodule.cpp

echo mv Golgi_nestmodule.h             golgimodule.h
mv Golgi_nestmodule.h             golgimodule.h

echo mv Golgi_golgimodule.sli          golgimodule.sli
mv Golgi_golgimodule.sli          golgimodule.sli

chmod u+x bootstrap.sh

./bootstrap.sh && \
./configure --with-nest=$NEST_DIR/bin/nest-config --with-sundials=$SUNDIALS_DIR/bin/sundials-config && \
make && \
make uninstall && \
make install
