#!/bin/sh

MODEL_NAME=$1
BUILD_DIR=$2

NEMO={{NEMO}}
NEURON_DIR={{NEURON_DIR}}

cd $BUILD_DIR

echo $NEMO -p --nmodl --nmodl-method=derivimplicit --nmodl-kinetic=Na_z Granule_DeSouza10.nemo
$NEMO -p --nmodl --nmodl-method=derivimplicit --nmodl-kinetic=Na_z Granule_DeSouza10.nemo

echo $NEMO --template=netstim_protocol.hoc Granule_DeSouza10.nemo
$NEMO --template=netstim_protocol.hoc Granule_DeSouza10.nemo

echo $NEMO --template=syn_template.hoc Granule_DeSouza10.nemo
$NEMO --template=syn_template.hoc Granule_DeSouza10.nemo

$NEURON_DIR/bin/nrnivmodl




