#!/bin/sh

MODEL_NAME=$1
BUILD_DIR=$2

NEST_DIR={{NEST_DIR}}
SUNDIALS_DIR={{SUNDIALS_DIR}}

cd $BUILD_DIR

LD_PRELOAD="libsundials_cvode.so libsundials_nvecserial.so libblas.so liblapack.so" \
LD_LIBRARY_PATH=$SUNDIALS_DIR/lib:$NEST_DIR/lib/nest time $NEST_DIR/bin/nest Golgi_testrun.sli



